module:
  address: 0
  admin_toolbar: 0
  automated_cron: 0
  awf_migration_group: 0
  awf_taxonomy_migration: 0
  backup_migrate: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  color: 0
  colorbox: 0
  comment: 0
  config: 0
  config_update: 0
  contact: 0
  context: 0
  context_ui: 0
  contextual: 0
  crop: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  dblog: 0
  diff: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  easy_install: 0
  editor: 0
  embed: 0
  entity_embed: 0
  entity_reference: 0
  entity_reference_revisions: 0
  eva: 0
  facets: 0
  features: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_entity: 0
  filter: 0
  focal_point: 0
  google_tag: 0
  help: 0
  history: 0
  image: 0
  image_widget_crop: 0
  imce: 0
  inline_entity_form: 0
  language: 0
  layout_discovery: 0
  link: 0
  mailchimp: 0
  mailsystem: 0
  mandrill: 0
  media: 0
  media_library: 0
  menu_block: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_open_graph: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_ui: 0
  migrate_plus: 0
  migrate_tools: 0
  migrate_upgrade: 0
  node: 0
  omega_tools: 0
  options: 0
  page_cache: 0
  panels: 0
  path: 0
  pathologic: 0
  plugin: 0
  plupload: 0
  prepopulate: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  reroute_email: 0
  rest: 0
  rules: 0
  search: 0
  search_api: 0
  search_api_attachments: 0
  serialization: 0
  shortcut: 0
  smtp: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  tour: 0
  typed_data: 0
  update: 0
  user: 0
  view_unpublished: 0
  viewfield: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  menu_link_content: 1
  pathauto: 1
  xmlsitemap: 1
  views: 10
  paragraphs: 11
  custom_search: 50
  context_metadata: 1000
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  awf: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
